In [1]:
import torch
import torch.nn as nn

In [74]:
a = torch.arange(6).reshape(2, 3)
b = torch.arange(6,12).reshape(2, 3)
print(a,"\n",b)

tensor([[0, 1, 2],
        [3, 4, 5]]) 
 tensor([[ 6,  7,  8],
        [ 9, 10, 11]])


In [75]:
print(torch.cat((a, b), dim=0))

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


In [77]:
x = torch.arange(36).reshape(6, 2, 3)
x

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29]],

        [[30, 31, 32],
         [33, 34, 35]]])

In [79]:
y = torch.split(x, 3, dim=0)
y = list(y)
y

[tensor([[[ 0,  1,  2],
          [ 3,  4,  5]],
 
         [[ 6,  7,  8],
          [ 9, 10, 11]],
 
         [[12, 13, 14],
          [15, 16, 17]]]),
 tensor([[[18, 19, 20],
          [21, 22, 23]],
 
         [[24, 25, 26],
          [27, 28, 29]],
 
         [[30, 31, 32],
          [33, 34, 35]]])]

In [80]:
z = [t.reshape(-1, t.size(-1)) for t in y]
print(z[0],"\n",z[1])

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]) 
 tensor([[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]])


In [81]:
[t for t in z for _ in range(3)]

[tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]),
 tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]),
 tensor([[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]),
 tensor([[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]),
 tensor([[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]),
 tensor([[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]])]

## 4D Code

In [170]:
grps = 2
size = 5

d1 = 2
d2 = grps * size
d3 = 4
d4 = 7

In [171]:
a = torch.arange(d1 * d2 * d3 * d4).reshape(d1, d2, d3, d4)
# a[0]

In [172]:
b = [torch.split(a[i], size, dim=0) for i in range(d1)]
b = [list(split) for split in b]
# b[0]

In [173]:
c = [[t.reshape(-1, t.size(-1)) for t in b[i]] for i in range(d1)]
# c[0]

In [174]:
d = [[t for t in c[i] for _ in range(size)] for i in range(d1)]
# d[0]

In [175]:
e = torch.stack([torch.stack(t) for t in d])
e.shape

torch.Size([2, 10, 20, 7])

In [176]:
e[0].shape

torch.Size([10, 20, 7])

In [177]:
e[0]

tensor([[[  0,   1,   2,  ...,   4,   5,   6],
         [  7,   8,   9,  ...,  11,  12,  13],
         [ 14,  15,  16,  ...,  18,  19,  20],
         ...,
         [119, 120, 121,  ..., 123, 124, 125],
         [126, 127, 128,  ..., 130, 131, 132],
         [133, 134, 135,  ..., 137, 138, 139]],

        [[  0,   1,   2,  ...,   4,   5,   6],
         [  7,   8,   9,  ...,  11,  12,  13],
         [ 14,  15,  16,  ...,  18,  19,  20],
         ...,
         [119, 120, 121,  ..., 123, 124, 125],
         [126, 127, 128,  ..., 130, 131, 132],
         [133, 134, 135,  ..., 137, 138, 139]],

        [[  0,   1,   2,  ...,   4,   5,   6],
         [  7,   8,   9,  ...,  11,  12,  13],
         [ 14,  15,  16,  ...,  18,  19,  20],
         ...,
         [119, 120, 121,  ..., 123, 124, 125],
         [126, 127, 128,  ..., 130, 131, 132],
         [133, 134, 135,  ..., 137, 138, 139]],

        ...,

        [[140, 141, 142,  ..., 144, 145, 146],
         [147, 148, 149,  ..., 151, 152, 153]

In [178]:
e[0][0]

tensor([[  0,   1,   2,   3,   4,   5,   6],
        [  7,   8,   9,  10,  11,  12,  13],
        [ 14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 28,  29,  30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47,  48],
        [ 49,  50,  51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60,  61,  62],
        [ 63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76],
        [ 77,  78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97],
        [ 98,  99, 100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118],
        [119, 120, 121, 122, 123, 124, 125],
        [126, 127, 128, 129, 130, 131, 132],
        [133, 134, 135, 136, 137, 138, 139]])

In [179]:
e[0][4]

tensor([[  0,   1,   2,   3,   4,   5,   6],
        [  7,   8,   9,  10,  11,  12,  13],
        [ 14,  15,  16,  17,  18,  19,  20],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 28,  29,  30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47,  48],
        [ 49,  50,  51,  52,  53,  54,  55],
        [ 56,  57,  58,  59,  60,  61,  62],
        [ 63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76],
        [ 77,  78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97],
        [ 98,  99, 100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109, 110, 111],
        [112, 113, 114, 115, 116, 117, 118],
        [119, 120, 121, 122, 123, 124, 125],
        [126, 127, 128, 129, 130, 131, 132],
        [133, 134, 135, 136, 137, 138, 139]])

In [180]:
e[0][5]

tensor([[140, 141, 142, 143, 144, 145, 146],
        [147, 148, 149, 150, 151, 152, 153],
        [154, 155, 156, 157, 158, 159, 160],
        [161, 162, 163, 164, 165, 166, 167],
        [168, 169, 170, 171, 172, 173, 174],
        [175, 176, 177, 178, 179, 180, 181],
        [182, 183, 184, 185, 186, 187, 188],
        [189, 190, 191, 192, 193, 194, 195],
        [196, 197, 198, 199, 200, 201, 202],
        [203, 204, 205, 206, 207, 208, 209],
        [210, 211, 212, 213, 214, 215, 216],
        [217, 218, 219, 220, 221, 222, 223],
        [224, 225, 226, 227, 228, 229, 230],
        [231, 232, 233, 234, 235, 236, 237],
        [238, 239, 240, 241, 242, 243, 244],
        [245, 246, 247, 248, 249, 250, 251],
        [252, 253, 254, 255, 256, 257, 258],
        [259, 260, 261, 262, 263, 264, 265],
        [266, 267, 268, 269, 270, 271, 272],
        [273, 274, 275, 276, 277, 278, 279]])

## Compress Code

In [183]:
INPUT = torch.arange(7987200).reshape(256, 325, 12, 8)

In [ ]:
X = [torch.split(INPUT[i], 5, dim=0) for i in range(256)]
X = [list(split) for split in X]
X = [[t.reshape(-1, t.size(-1)) for t in X[i]] for i in range(256)]
X = [[t for t in X[i] for _ in range(5)] for i in range(256)]
X = torch.stack([torch.stack(t) for t in X])
X.shape
print(X)
del X

print(INPUT)

torch.Size([256, 325, 60, 8])

In [2]:
INPUT = torch.arange(560).reshape(2, 10, 4, 7)

In [3]:
X = torch.stack([torch.stack(t1) for t1 in [[t2 for t2 in [[t3.reshape(-1, t3.size(-1)) for t3 in [list(split) for split in [torch.split(INPUT[k], size, dim=0) for k in range(256)]][j]] for j in range(256)][i] for _ in range(size)] for i in range(256)]])

NameError: name 'size' is not defined